"""
calibrate.py — timed monochrome calibration + auto-config generation (no input required)

Use this when you cannot send commands to the device via serial.

What it does:
1) Initializes the camera in GRAYSCALE/QVGA.
2) Samples BACKGROUND statistics for N seconds (make sure the ball is NOT in ROI).
3) Waits a short "swap" interval (place the ball in ROI).
4) Samples OBJECT statistics for N seconds (ball should fill most of ROI).
5) Computes a recommended GRAY_THRESHOLD based on background/object midpoint.
6) Writes `color_config_auto.py` to the device filesystem so `main.py` can
   auto-import it on the next run.

Notes:
- This is designed for a black-and-white camera using intensity segmentation.
- If your ball is darker than the background, threshold will be (0, hi).
- If your ball is brighter than the background, threshold will be (lo, 255).
- `color_config_auto.py` is generated on-device and should NOT be committed.
"""

import time

import sensor

# -----------------------------------------------------------------------------
# Tunables
# -----------------------------------------------------------------------------

# ROI size (fraction of frame). Smaller ROI reduces background mixing.
ROI_W_FRAC = 0.20
ROI_H_FRAC = 0.20

# Sampling durations (seconds)
BACKGROUND_SAMPLE_S = 3.0
OBJECT_SAMPLE_S = 3.0

# Time between phases to reposition the ball (seconds)
SWAP_INTERVAL_S = 2.0

# Safety margin applied around the midpoint threshold (intensity units).
# Increase if the ball is intermittently lost; decrease if too much background
# is included as "ball".
MARGIN_INTENSITY = 8

# Config defaults written to color_config_auto.py
DEFAULT_PIXELS_THRESHOLD = 150
DEFAULT_AREA_THRESHOLD = 150
DEFAULT_MERGE = True
DEFAULT_MARGIN = 10
DEFAULT_DRAW_OVERLAY = True
DEFAULT_DRAW_RECT = False

DEFAULT_AUTO_GAIN = True
DEFAULT_AUTO_EXPOSURE = True
DEFAULT_AUTO_WHITEBAL = True

# -----------------------------------------------------------------------------
# Helpers
# -----------------------------------------------------------------------------


def _clamp(v, lo, hi):
    if v < lo:
        return lo
    if v > hi:
        return hi
    return v


def _roi_from_sensor():
    w = sensor.width()
    h = sensor.height()
    rw = _clamp(int(w * ROI_W_FRAC), 8, w)
    rh = _clamp(int(h * ROI_H_FRAC), 8, h)
    rx = (w - rw) // 2
    ry = (h - rh) // 2
    return (rx, ry, rw, rh)


def _sample_stats_for_seconds(roi, duration_s):
    """
    Average mean and stdev across frames for the given duration.
    Returns: (mean_avg, stdev_avg, n_frames)
    """
    t0 = time.ticks_ms()
    mean_sum = 0.0
    std_sum = 0.0
    n = 0

    while True:
        img = sensor.snapshot()
        img.draw_rectangle(roi, color=255, thickness=1)
        cx = roi[0] + roi[2] // 2
        cy = roi[1] + roi[3] // 2
        img.draw_cross(cx, cy, color=255, size=8, thickness=1)

        st = img.get_statistics(roi=roi)
        mean_sum += st.l_mean()
        std_sum += st.l_stdev()
        n += 1

        if time.ticks_diff(time.ticks_ms(), t0) >= int(duration_s * 1000):
            break

    if n <= 0:
        return 0.0, 0.0, 0

    return mean_sum / n, std_sum / n, n


def _recommend_threshold(bg_mean, obj_mean):
    """
    Returns: (gray_threshold_tuple, mode_string, midpoint_int)
      mode_string is "dark" or "bright"
    """
    mid = int((bg_mean + obj_mean) / 2)
    mid = _clamp(mid, 0, 255)

    if obj_mean < bg_mean:
        # Object darker than background
        hi = _clamp(mid + MARGIN_INTENSITY, 0, 255)
        return (0, hi), "dark", mid
    else:
        # Object brighter than background
        lo = _clamp(mid - MARGIN_INTENSITY, 0, 255)
        return (lo, 255), "bright", mid


def _write_auto_config(gray_threshold, roi, bg_mean, obj_mean, mode, midpoint):
    """
    Writes color_config_auto.py to device filesystem.
    """
    lines = [
        '"""',
        "AUTO-GENERATED FILE — DO NOT EDIT BY HAND",
        "",
        "Generated by `firmware/calibrate.py` (timed calibration).",
        "This file overrides `firmware/color_config.py` when present.",
        '"""',
        "",
        "# Grayscale threshold tuple (lo, hi) in [0, 255]",
        "GRAY_THRESHOLD = ({}, {})".format(
            int(gray_threshold[0]), int(gray_threshold[1])
        ),
        "",
        "# Blob filtering",
        "PIXELS_THRESHOLD = {}".format(int(DEFAULT_PIXELS_THRESHOLD)),
        "AREA_THRESHOLD = {}".format(int(DEFAULT_AREA_THRESHOLD)),
        "MERGE = {}".format("True" if DEFAULT_MERGE else "False"),
        "MARGIN = {}".format(int(DEFAULT_MARGIN)),
        "",
        "# Optional ROI restriction (None = full frame search)",
        "ROI = None",
        "",
        "# Sensor auto-controls",
        "AUTO_GAIN = {}".format("True" if DEFAULT_AUTO_GAIN else "False"),
        "AUTO_EXPOSURE = {}".format("True" if DEFAULT_AUTO_EXPOSURE else "False"),
        "AUTO_WHITEBAL = {}".format("True" if DEFAULT_AUTO_WHITEBAL else "False"),
        "",
        "# Overlay / debug",
        "DRAW_OVERLAY = {}".format("True" if DEFAULT_DRAW_OVERLAY else "False"),
        "DRAW_RECT = {}".format("True" if DEFAULT_DRAW_RECT else "False"),
        "",
        "# Calibration metadata (for reference)",
        "CALIBRATION_ROI = ({},{},{},{})".format(roi[0], roi[1], roi[2], roi[3]),
        "CALIBRATION_BACKGROUND_MEAN = {:.3f}".format(bg_mean),
        "CALIBRATION_OBJECT_MEAN = {:.3f}".format(obj_mean),
        "CALIBRATION_MODE = {!r}".format(mode),
        "CALIBRATION_MIDPOINT = {}".format(int(midpoint)),
        "CALIBRATION_MARGIN_INTENSITY = {}".format(int(MARGIN_INTENSITY)),
        "",
    ]

    with open("color_config_auto.py", "w") as f:
        f.write("\n".join(lines))


# -----------------------------------------------------------------------------
# Main
# -----------------------------------------------------------------------------

sensor.reset()
sensor.set_pixformat(sensor.GRAYSCALE)
sensor.set_framesize(sensor.QVGA)
sensor.skip_frames(time=2000)

# For calibration, leave auto controls enabled by default so the threshold
# reflects real operating conditions.
if hasattr(sensor, "set_auto_gain"):
    sensor.set_auto_gain(True)
if hasattr(sensor, "set_auto_exposure"):
    sensor.set_auto_exposure(True)
if hasattr(sensor, "set_auto_whitebal"):
    sensor.set_auto_whitebal(True)

roi = _roi_from_sensor()

print("CALIBRATE_TIMED_START")
print("ROI:{},{},{},{}".format(roi[0], roi[1], roi[2], roi[3]))
print(
    "Step 1/3: BACKGROUND sampling for {:.1f}s (keep ball OUT of ROI)".format(
        BACKGROUND_SAMPLE_S
    )
)

bg_mean, bg_std, bg_n = _sample_stats_for_seconds(roi, BACKGROUND_SAMPLE_S)
print("BACKGROUND: mean={:.2f} std={:.2f} n={}".format(bg_mean, bg_std, bg_n))

print("Step 2/3: Swap interval {:.1f}s (place ball IN ROI now)".format(SWAP_INTERVAL_S))
time.sleep(SWAP_INTERVAL_S)

print(
    "Step 3/3: OBJECT sampling for {:.1f}s (ball should fill ROI)".format(
        OBJECT_SAMPLE_S
    )
)
obj_mean, obj_std, obj_n = _sample_stats_for_seconds(roi, OBJECT_SAMPLE_S)
print("OBJECT: mean={:.2f} std={:.2f} n={}".format(obj_mean, obj_std, obj_n))

thr, mode, midpoint = _recommend_threshold(bg_mean, obj_mean)

print("Recommendation:")
print(
    "  mode={} (object {} than background)".format(
        mode, "darker" if mode == "dark" else "brighter"
    )
)
print("  midpoint={} margin={}".format(midpoint, MARGIN_INTENSITY))
print("  GRAY_THRESHOLD = ({}, {})".format(thr[0], thr[1]))

_write_auto_config(thr, roi, bg_mean, obj_mean, mode, midpoint)
print("Wrote color_config_auto.py")
print("Now run firmware/main.py; it should prefer color_config_auto.py if present.")
