"""
calibrate.py — interactive monochrome calibration that generates color_config_auto.py

This script is designed for black-and-white tracking using grayscale intensity
thresholding. It guides you through taking two samples:

  1) Background: ROI contains NO ball
  2) Object:     ball fills most of the ROI

It then computes a recommended threshold and writes `color_config_auto.py`
to the device filesystem so `main.py` can automatically pick it up.

Expected workflow:
- Open this file in OpenMV IDE and click Run
- Use the Serial Terminal in OpenMV IDE:
    - Press 'b' to sample background
    - Press 'o' to sample object (ball)
    - Press 'w' to write color_config_auto.py
    - Press 'p' to print current recommendation again

Important:
- `color_config_auto.py` is meant to be generated; do NOT commit it to git.
- For best results, keep lighting stable while sampling.

Output:
- Prints sample means/stddevs and the computed GRAY_THRESHOLD.
"""

import time

import sensor
from pyb import USB_VCP

# -----------------------------------------------------------------------------
# Tunables
# -----------------------------------------------------------------------------

# ROI size as fraction of frame size. Smaller ROI reduces background mixing.
ROI_W_FRAC = 0.20
ROI_H_FRAC = 0.20

# Number of frames averaged per sample capture.
SAMPLES_PER_CAPTURE = 40

# Safety margin applied around the midpoint threshold.
# Increase if detection is unstable; decrease if ball edges are missed.
MARGIN_INTENSITY = 8

# Defaults written into color_config_auto.py in addition to GRAY_THRESHOLD.
DEFAULT_PIXELS_THRESHOLD = 150
DEFAULT_AREA_THRESHOLD = 150
DEFAULT_MERGE = True
DEFAULT_MARGIN = 10
DEFAULT_DRAW_OVERLAY = True
DEFAULT_DRAW_RECT = False

# Sensor control defaults written to auto config.
DEFAULT_AUTO_GAIN = True
DEFAULT_AUTO_EXPOSURE = True
DEFAULT_AUTO_WHITEBAL = True


# -----------------------------------------------------------------------------
# Helpers
# -----------------------------------------------------------------------------


def _clamp(v, lo, hi):
    if v < lo:
        return lo
    if v > hi:
        return hi
    return v


def _roi_from_sensor():
    w = sensor.width()
    h = sensor.height()
    rw = _clamp(int(w * ROI_W_FRAC), 8, w)
    rh = _clamp(int(h * ROI_H_FRAC), 8, h)
    rx = (w - rw) // 2
    ry = (h - rh) // 2
    return (rx, ry, rw, rh)


def _mean_and_std_for_roi(roi, n_frames):
    # Collect mean/std across frames and average them. Std averaging is an
    # approximation, but good enough for calibration guardrails.
    mean_sum = 0.0
    std_sum = 0.0

    for _ in range(n_frames):
        img = sensor.snapshot()
        stats = img.get_statistics(roi=roi)
        mean_sum += stats.l_mean()
        std_sum += stats.l_stdev()

    return (mean_sum / n_frames, std_sum / n_frames)


def _recommend_threshold(bg_mean, obj_mean):
    """
    Compute GRAY_THRESHOLD based on which side of the background the object lies.

    Returns:
      (threshold_tuple, mode_string)

    mode_string:
      - "dark"   -> object darker than background -> threshold (0, hi)
      - "bright" -> object brighter than background -> threshold (lo, 255)
    """
    mid = int((bg_mean + obj_mean) / 2)
    mid = _clamp(mid, 0, 255)

    if obj_mean < bg_mean:
        # Object is darker: select low intensities up to mid (+ margin)
        hi = _clamp(mid + MARGIN_INTENSITY, 0, 255)
        return (0, hi), "dark"
    else:
        # Object is brighter: select high intensities from mid (- margin)
        lo = _clamp(mid - MARGIN_INTENSITY, 0, 255)
        return (lo, 255), "bright"


def _write_auto_config(gray_threshold, roi):
    """
    Write firmware/color_config_auto.py onto the device filesystem.
    """
    content_lines = [
        '"""',
        "AUTO-GENERATED FILE — DO NOT EDIT BY HAND",
        "",
        "Generated by `firmware/calibrate.py` on the OpenMV device.",
        "This file overrides `firmware/color_config.py` when present.",
        '"""',
        "",
        "# Grayscale threshold tuple (lo, hi) in [0, 255]",
        "GRAY_THRESHOLD = ({}, {})".format(
            int(gray_threshold[0]), int(gray_threshold[1])
        ),
        "",
        "# Blob filtering",
        "PIXELS_THRESHOLD = {}".format(int(DEFAULT_PIXELS_THRESHOLD)),
        "AREA_THRESHOLD = {}".format(int(DEFAULT_AREA_THRESHOLD)),
        "MERGE = {}".format("True" if DEFAULT_MERGE else "False"),
        "MARGIN = {}".format(int(DEFAULT_MARGIN)),
        "",
        "# Optional ROI restriction; keep None unless you want to lock it down",
        "# Format: (x, y, w, h)",
        "ROI = {}".format("None"),
        "",
        "# Sensor auto-controls",
        "AUTO_GAIN = {}".format("True" if DEFAULT_AUTO_GAIN else "False"),
        "AUTO_EXPOSURE = {}".format("True" if DEFAULT_AUTO_EXPOSURE else "False"),
        "AUTO_WHITEBAL = {}".format("True" if DEFAULT_AUTO_WHITEBAL else "False"),
        "",
        "# Overlay / debug",
        "DRAW_OVERLAY = {}".format("True" if DEFAULT_DRAW_OVERLAY else "False"),
        "DRAW_RECT = {}".format("True" if DEFAULT_DRAW_RECT else "False"),
        "",
        "# Calibration metadata (for reference)",
        "CALIBRATION_ROI = ({},{},{},{})".format(roi[0], roi[1], roi[2], roi[3]),
        "",
    ]

    # Write to the filesystem root; OpenMV import resolves in working dir/root.
    with open("color_config_auto.py", "w") as f:
        f.write("\n".join(content_lines))


def _print_help():
    print("")
    print("Commands:")
    print("  b : sample BACKGROUND (no ball in ROI)")
    print("  o : sample OBJECT (ball fills ROI)")
    print("  p : print current recommendation")
    print("  w : write color_config_auto.py (requires b + o)")
    print("  h : help")
    print("")


# -----------------------------------------------------------------------------
# Sensor init (GRAYSCALE proven responsive on your hardware)
# -----------------------------------------------------------------------------

sensor.reset()
sensor.set_pixformat(sensor.GRAYSCALE)
sensor.set_framesize(sensor.QVGA)
sensor.skip_frames(time=2000)

# NOTE: For calibration we intentionally do NOT force auto controls off.
# Leaving them enabled tends to reflect the actual operating conditions.

clock = time.clock()
vcp = USB_VCP()
roi = _roi_from_sensor()

bg = None  # (mean, std)
obj = None  # (mean, std)

print("CALIBRATE_INTERACTIVE_START")
print("ROI:{},{},{},{}".format(roi[0], roi[1], roi[2], roi[3]))
_print_help()

# -----------------------------------------------------------------------------
# Main loop
# -----------------------------------------------------------------------------

while True:
    clock.tick()
    img = sensor.snapshot()

    # Draw ROI overlay so you can position the ball properly.
    img.draw_rectangle(roi, color=255, thickness=1)
    cx = roi[0] + roi[2] // 2
    cy = roi[1] + roi[3] // 2
    img.draw_cross(cx, cy, color=255, size=8, thickness=1)

    # Non-blocking read of a single command byte from USB VCP.
    if vcp.any():
        raw = vcp.read(1)
        if not raw:
            continue

        try:
            cmd = raw.decode("utf-8").lower()
        except Exception:
            cmd = ""

        if cmd == "h":
            _print_help()

        elif cmd == "b":
            print("Sampling BACKGROUND... (keep ROI clear)")
            bg = _mean_and_std_for_roi(roi, SAMPLES_PER_CAPTURE)
            print("BACKGROUND mean={:.1f} std={:.1f}".format(bg[0], bg[1]))

        elif cmd == "o":
            print("Sampling OBJECT... (ball fills ROI)")
            obj = _mean_and_std_for_roi(roi, SAMPLES_PER_CAPTURE)
            print("OBJECT mean={:.1f} std={:.1f}".format(obj[0], obj[1]))

        elif cmd == "p":
            if (bg is None) or (obj is None):
                print("Need both samples first. Press 'b' then 'o'.")
            else:
                thr, mode = _recommend_threshold(bg[0], obj[0])
                print(
                    "Mode: {} (object {} than background)".format(
                        mode, "darker" if mode == "dark" else "brighter"
                    )
                )
                print("Recommended GRAY_THRESHOLD = ({}, {})".format(thr[0], thr[1]))
                print(
                    "bg_mean={:.1f} obj_mean={:.1f} margin={}".format(
                        bg[0], obj[0], MARGIN_INTENSITY
                    )
                )

        elif cmd == "w":
            if (bg is None) or (obj is None):
                print("Need both samples first. Press 'b' then 'o'.")
            else:
                thr, mode = _recommend_threshold(bg[0], obj[0])
                _write_auto_config(thr, roi)
                print("Wrote color_config_auto.py")
                print(
                    "Mode: {} | GRAY_THRESHOLD = ({}, {})".format(mode, thr[0], thr[1])
                )
                print(
                    "Now run firmware/main.py; it should prefer color_config_auto.py."
                )

        else:
            # Ignore other characters (like newlines) to keep interaction smooth.
            pass
