"""
firmware/color_config.py

Monochrome (grayscale) blob-tracking configuration.

This project originally supported LAB (color) thresholds, but the current
hardware is a black-and-white camera. We therefore detect the ball using
grayscale intensity segmentation and blob filtering.

Auto-config override:
- `main.py` will try to import `color_config_auto.py` first (if present),
  and fall back to this file.
- `color_config_auto.py` is intended to be generated by `calibrate.py`
  and SHOULD NOT be committed to git.

Key values to tune:
- GRAY_THRESHOLD: intensity range to segment the ball
- PIXELS_THRESHOLD / AREA_THRESHOLD: filters to suppress noise blobs
- ROI: optionally restrict search to a region (x, y, w, h) in pixels
"""

# -----------------------------------------------------------------------------
# Thresholding (grayscale)
# -----------------------------------------------------------------------------
# OpenMV grayscale threshold tuple format: (lo, hi) within [0, 255]
#
# Choose a range that selects the ball:
# - Dark ball on lighter background: (0, hi)
# - Bright ball on darker background: (lo, 255)
#
# Start here and tune after observing blob detection stability.
GRAY_THRESHOLD = (0, 70)

# -----------------------------------------------------------------------------
# Blob filtering
# -----------------------------------------------------------------------------
# Minimum number of pixels in the thresholded blob to be considered.
PIXELS_THRESHOLD = 150

# Minimum area (in pixels) of the blob's bounding box to be considered.
AREA_THRESHOLD = 150

# Merge nearby blobs into one. Usually helpful for slightly fragmented masks.
MERGE = True

# Merge margin (pixels) when MERGE is enabled.
MARGIN = 10

# Optional region-of-interest restriction for faster/more stable tracking.
# If None, search full frame.
# Format: (x, y, w, h)
ROI = None

# -----------------------------------------------------------------------------
# Sensor auto-controls
# -----------------------------------------------------------------------------
# For monochrome segmentation, leaving these enabled often provides the most
# stable results across lighting changes. If you need absolute stability for a
# fixed lighting environment, you can disable them.
AUTO_GAIN = True
AUTO_EXPOSURE = True
# White balance is irrelevant for GRAYSCALE on many builds, but kept for
# compatibility if the API exists.
AUTO_WHITEBAL = True

# -----------------------------------------------------------------------------
# Overlay / debug behavior
# -----------------------------------------------------------------------------
# Draw debugging overlays on the framebuffer (circle/cross/rect) when a blob is
# detected. This does not affect serial output.
DRAW_OVERLAY = True

# If true, also draw the blob bounding rectangle in addition to circle/cross.
DRAW_RECT = False
